### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by lighter-cn** [lighter-cn/protospace-32501#1]
# URL
https://protospace-32501.herokuapp.com/

**Comment by spoongit** [comment]
田中（lighter-cn）さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by lighter-cn** [comment]
ご確認ありがとうございます！

最終課題の案内が届きましたので、引き続き進めて参ります！
